version: "3"

networks:
  dev-network:
    driver: bridge

services:
  coopvote_db:
    image: postgres:15.1
    container_name: coopvote_db
    networks:
      - dev-network
    restart: always
    environment:
      - POSTGRES_DB=coopvote_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

  vote-rabbit:
    image: rabbitmq:3-management
    container_name: vote-rabbit
    networks:
      - dev-network
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672