server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
spring:
  application:
    name: coopvote
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:coopvote_db}?currentSchema=dev
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}
    initialization-mode: always
    initialize: true
    platform: postgresql

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    locations: classpath:db/migration
    schemas: dev