CREATE TABLE VOTING_SESSION (
  ID BIGSERIAL PRIMARY KEY,
  ID_TOPIC BIGSERIAL NOT NULL,
  OPENING_DATE TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  DURATION_MINUTES INTEGER,
  IS_OPEN BOOLEAN DEFAULT TRUE,
  FOREIGN KEY (ID_TOPIC) REFERENCES TOPIC(id)
);
